language: python
sudo: required

services:
  - docker

addons:
  ssh_known_hosts: wheelhouse.acsone.eu

env:
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PY_VER=cp27-cp27mu REQS="requirements-odoo-latest.txt requirements-odoo8.txt requirements-odoo9.txt requirements-oca.txt"

before_install:
  - openssl aes-256-cbc -K $encrypted_3af06edbe5cf_key -iv $encrypted_3af06edbe5cf_iv -in deploy_rsa.enc -out deploy_rsa -d
  - chmod 600 deploy_rsa

install:
  - docker pull $DOCKER_IMAGE
  - ./download.sh

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh $PY_VER $REQS
  - rsync -avz -e 'ssh -i deploy_rsa' ./wheelhouse/ "manylinux@wheelhouse.acsone.eu:"
