notifications:
  email: false

sudo: required
services:
  - docker

matrix:
  include:
    - env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 
           PY_VER=cp27-cp27mu

#    - env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
#           PRE_CMD=linux32
#           PY_VER=cp27-cp27mu

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run -e "PY_VER=$PY_VER" --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
