notifications:
  email: false

matrix:
  include:
    sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
         PY_VER=cp27-cp27mu

install:
  - docker pull $DOCKER_IMAGE

script:
  - ./download.sh
  - docker run -e "PY_VER=$PY_VER" --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh
  - ls wheelhouse/
 
#  - export SSHPASS=$RSYNC_PASS
#- sshpass -e rsync -avz wheelhouse/ $RSYNC_USER@wheelhouse.acsone.eu:
