language: python
sudo: required
notifications:
  email: false

services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PY_VER=cp27-cp27mu REQS="requirements-odoo8.txt requirements-odoo9.txt requirements-oca.txt"
  global:
    secure: "ryWK6XyF08Ps6youYQHVIMYh5ulmMY135al8fxTtJjDoR4z9ruR/RW6y+MdAONyWgvLeTSrEDcygf137GDobXjhPAzvSuO/Obvn6ja9p3ia69GFaPo/GzGT4QQKqJIlUZi8ooUYMb9VzZVVMxzS/L8azrZKGNTYY22id6idYDoxL8jeuvoYDx5wf7RCG21Aw2eHSPdPhmmC+K6Aiw2dYbKP09KsqWTQIqlVUq762CviNaz48J9coWL5QPvR49i0/pd8hk0MlaEc2uYA34nLk07LW77k1Mqt1h4YC57nJa2zJo5rwOfxAUIrNRqlBjeq64HOWMF95u/A2UpvIVQ5Lmsthz1p+r5dIl6rUVNWGuQMF+GqNYLlE9BbUJ4W9CMeiRRKejD6poq/mAiidj+TKfhpR6qVrbC9BwdyZTZHu8BmyTdMimh3ogMkxNQHh6uZyvEbzQVRchWaaAXjhK3nbjL7gzR738VScumMAuHpT6y9UKK3nEQTe0MTKt+TmRQvJwYJBH4jNq8GSPr2Zb8LvWbCfOUExHtd3eQ6lnUB6dIC6fBigRT1ai5BF9yJLBuiyZH6JbQuI5jNapygnHvh2fK8HxArBylQShAE9zCL02jrOSlHbdrcq17kbfk4WovFhsVeC2lBv/jPRSkRUaaWiHbnebUo5D4HKp3NiVJ1vcWE="

before_install:
  - sudo apt-get install -qq sshpass

install:
  - docker pull $DOCKER_IMAGE
    #- ./download.sh

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh $PY_VER $REQS
  - sshpass -e rsync -avz ./wheelhouse/ $SSHUSER@wheelhouse.acsone.eu:/var/www/wheelhouse/manylinux1/
