language: python
sudo: required
notifications:
  email: false

services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PY_VER=cp27-cp27mu REQS="requirements-odoo8.txt requirements-odoo9.txt requirements-oca.txt"
  global:
    secure: "uGWAsE6khpOqYxF9HFGIkf3kgGdkVv/TpoputHCCIupX9J5f/EcSyeJpyxxCNXCxwTfXV/KJnaCqgU0QLm3lv3Ey51zE1VVdnib8YiDqfm0TMKrcH+dYw3aj+pCryenfD7FYm9poMnWLvUDvqaBhAjEo4Xf+xHakgeax3TXLYVl7UqRy2im8PIEcUEJBwtogzcK+cr9sctP3Hyt5WxBAmm1lGYkqTLn8ldtY4PSFkDzrft/QzqPlFNAYHtg9PuMwryLjNe/nHl/nfrLB9m0zkE6mWGnkxsJi/wnEJzMiMG/4VFlWQi6+eX7GVdxMj4wj4eH2fVzotFzg1fQdLhYGODU0meRfs0Lis/aNPzf4e3gnKN/wktfvh06DpPYdCoZ2R9LrEmYO8Je5gVeII7WvaVh42mHEGnzOqDonZj6sxq7lWT0y8M+Nqm59XKP9RBoFip04iniSQ8CgeIJ9aZDFlfHZywsRHGoh/RcoevPRk6QSMoN+pN6bx9s8EJfsCD+Gya7JL5ZngHxdz+aXlBtjqww8YtES+GvcxC8RenneptVWj3Dkj7cD1JiPb3yBmyWHYM+iRk5asn5dLTRNW99cqgGpSLTNDaP2KOJWytKkz5a33Rzn7lkjikgGCtz+xDyIpbGEx3ruJGe2OkvoJzrj/idF1Pt7zx0wb8N+JSgIubQ="

before_install:
  - sudo apt-get install -qq sshpass

install:
  - docker pull $DOCKER_IMAGE
    #- ./download.sh

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh $PY_VER $REQS
  - sshpass -e rsync -avz ./wheelhouse/ $SSHUSER@wheelhouse.acsone.eu:/var/www/wheelhouse/manylinux1/
