name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - MANYLINUX_VER: manylinux2014_x86_64
            DOCKER_IMAGE: quay.io/pypa/manylinux2014_x86_64
            PY_VER: cp36-cp36m
            PRE_INSTALL: "'setuptools<58'"
            REQS: "requirements3.6.txt requirements3-other.txt requirements3-latest.txt requirements3-oca.txt requirements3-odoo12.txt requirements3-odoo13.txt"
          - MANYLINUX_VER: manylinux2014_x86_64
            DOCKER_IMAGE: quay.io/pypa/manylinux2014_x86_64
            PY_VER: cp38-cp38
            PRE_INSTALL: "setuptools"
            REQS: "requirements3-other.txt requirements3-latest.txt requirements3-oca.txt requirements3-odoo13.txt requirements3-odoo14.txt requirements3-odoo15.txt requirements3-odoomaster.txt"
          - MANYLINUX_VER: manylinux2014_x86_64
            DOCKER_IMAGE: quay.io/pypa/manylinux2014_x86_64
            PY_VER: cp39-cp39
            PRE_INSTALL: "setuptools"
            REQS: "requirements3-other.txt requirements3-latest.txt requirements3-oca.txt requirements3-odoo14.txt requirements3-odoo15.txt requirements3-odoomaster.txt"
    env:
      MANYLINUX_VER: ${{ matrix.MANYLINUX_VER }}
      DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
      PY_VER: ${{ matrix.PY_VER }}
      PRE_INSTALL: "${{ matrix.PRE_INSTALL }}"
      REQS: ${{ matrix.REQS }}
    steps:
      - uses: actions/checkout@v2
      - name: Download dependencies
        run: ./download.sh
      - name: Build
        run: docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/build-wheels.sh $PY_VER "$PRE_INSTALL" $MANYLINUX_VER $REQS
      - name: Result
        run: ls -al wheelhouse/
      - name: Publish
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.SSH_DEPLOY_KEY }}")
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./wheelhouse/ "manylinux@wheelhouse.acsone.eu:"
        if: ${{ github.event_name == 'push' }}
