name: CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - MANYLINUX_VER: manylinux2014_x86_64
            DOCKER_IMAGE: quay.io/pypa/manylinux2014_x86_64
            PY_VER: cp36-cp36m
            REQS: "requirements3-other.txt requirements3-latest.txt requirements3-oca.txt requirements3-odoo11.txt requirements3-odoo12.txt requirements3-odoo13.txt"
          - MANYLINUX_VER: manylinux2014_x86_64
            DOCKER_IMAGE: quay.io/pypa/manylinux2014_x86_64
            PY_VER: cp38-cp38
            REQS: "requirements3-other.txt requirements3-latest.txt requirements3-oca.txt requirements3-odoo13.txt requirements3-odoo14.txt requirements3-odoomaster.txt"
    env:
      MANYLINUX_VER: ${{ matrix.MANYLINUX_VER }}
      DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
      PY_VER: ${{ matrix.PY_VER }}
      REQS: ${{ matrix.REQS }}
    steps:
      - uses: actions/checkout@v2
      - name: Download dependencies
        run: ./download.sh
      - name: Build
        run: docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/build-wheels.sh $PY_VER $MANYLINUX_VER $REQS
      - name: Result
        run: ls -al wheelhouse/
